spring:
  application:
    name: local-grpc-server
grpc:
  server:
    port: 9898
  client:
    GLOBAL:
      address: 'static://[::1]:50052'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext