server:
  port: 8080
spring:
  application:
    name: local-grpc-client

grpc:
  client:
    GLOBAL:
      address: 'static://[::1]:50051'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext
